openapi: '3.0.0'
info:
  version: 0.1.0
  title: Store API docs
  description: store-9 team's api docs
servers:
  - url: http://localhost:4000/
paths:
  /user:
    get:
      summary: Returns user list
      responses:
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  parameters: {}
  schemas:
    User:
      type: object
      required:
        - _id
        - name
      properties:
        _id:
          type: number
          description: id
        name:
          type: string
          description: 유저 이름
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 내부 오류
